name: Android publish CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build before
      run: ls -ll
    - name: Build Setup 1 GaiaXAndroidClientToStudio
      run: cd ./GaiaXAndroidClientToStudio && chmod +x ./gradlew && ./gradlew clean assembleDebug -Ptype=debug -Pgroup=com.github.alibaba.GaiaX -Pversion=dev-SNAPSHOT -xtest -xlint publishToMavenLocal
    - name: Build Setup 2 GaiaXAnalyze
      run: cd ./GaiaXAnalyze/GXAnalyzeAndroid && chmod +x ./gradlew && ./gradlew clean assembleDebug -Ptype=debug -Pgroup=com.github.alibaba.GaiaX -Pversion=dev-SNAPSHOT -xtest -xlint publishToMavenLocal
    - name: Build Setup 3 GaiaXAndroid 
      run: cd ./GaiaXAndroid && chmod +x ./gradlew && ./gradlew clean assembleDebug -Ptype=debug -Pgroup=com.github.alibaba.GaiaX -Pversion=dev-SNAPSHOT -xtest -xlint publishToMavenLocal
    - name: Build Setup 4 GaiaXAndroidAdapter 
      run: cd ./GaiaXAndroidAdapter && chmod +x ./gradlew && ./gradlew clean assembleDebug -Ptype=debug -Pgroup=com.github.alibaba.GaiaX -Pversion=dev-SNAPSHOT -xtest -xlint publishToMavenLocal
    - name: Build Setup 5 GaiaXAndroidQuickJS 
      run: cd ./GaiaXAndroidQuickJS && chmod +x ./gradlew && ./gradlew clean assembleDebug -Ptype=debug -Pgroup=com.github.alibaba.GaiaX -Pversion=dev-SNAPSHOT -xtest -xlint publishToMavenLocal
    - name: Build Setup 6 GaiaXAndroidJS 
      run: cd ./GaiaXAndroidJS && chmod +x ./gradlew && ./gradlew clean assembleDebug -Ptype=debug -Pgroup=com.github.alibaba.GaiaX -Pversion=dev-SNAPSHOT -xtest -xlint publishToMavenLocal
    - name: Build Setup 7 GaiaXAndroidJSProxy 
      run: cd ./GaiaXAndroidJSProxy && chmod +x ./gradlew && ./gradlew clean assembleDebug -Ptype=debug -Pgroup=com.github.alibaba.GaiaX -Pversion=dev-SNAPSHOT -xtest -xlint publishToMavenLocal